import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Article, loadArticles } from "../lib/articles";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  const articles = await loadArticles();
  return {
    props: {
      articles,
    },
  };
}

type HomeProps = {
  articles: Article[];
};

const Home: NextPage = (props: HomeProps) => {
  console.log(props.articles);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {props.articles.map((article) => (
          <div key={article.name}>
            <Link href={`articles/${article.name}`}>{article.name}</Link>
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
